
CREATE PROCEDURE SP_SATISLAR
AS
SELECT SATISID, URUNAD, PERSONELAD + ' ' + PERSONELSOYAD AS 'PERSONEL', MUSTERIAD + ' ' + MUSTERISOYAD AS 'MUSTERI' FROM TBLSATIS 
INNER JOIN TBLURUN ON TBLSATIS.URUN = TBLURUN.URUNID
INNER JOIN TBLPERSONEL ON TBLSATIS.PERSONEL = TBLPERSONEL.PERSONELID 
INNER JOIN TBLMUSTERI ON TBLSATIS.MUSTERI = TBLMUSTERI.MUSTERIID

--EXECUTE SP_SATISLAR