
USE DBPERSONEL

CREATE PROCEDURE DEPARTMANLISTESI
AS
SELECT PERSONELID, PERSONELAD, PERSONELSOYAD, DEPARTMANAD, PERSONELMAAS, PERSONELFOTOGRAF FROM TBLPERSONEL 
INNER JOIN TBLDEPARTMAN 
ON TBLPERSONEL.PERSONELDEPARTMAN = TBLDEPARTMAN.DEPARTMANID

--EXECUTE DEPARTMANLISTESI